version: '3.8'
services:
  pgdb:
    build: pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
  web:
    build: app
    command: python app.py
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    depends_on:
      - pgdb
volumes:
  postgres_data: